name = "TF2 Craft Mod Server"
author = "AqueousDog"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4657d4fb4d698898f6aa1c4a7ac7a516b34f5c2e511daff29fbdad99cf588bad"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.105"
